"use client"
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { usePathname } from "next/navigation";
import Navbar from "@/components/Navbar";;

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pathname = usePathname();
  if (pathname === "/login" || pathname === "/signup") {
    return (
      <html lang="en" className="dark">
        <body className={inter.className}>
          {children}
        </body>
      </html>
    );
  } else {
    return (
      <html lang="en" className="dark">
        <body className={inter.className}>
          <Navbar />
          {children}
        </body>
      </html>
    );
  }
}
